
----- CREATENG BADTABASE ODI_CRICKET
CREATE DATABASE  IF NOT EXISTS ODI_CRICKET;
-- USING DATABASE 
USE ODI_CRICKET;

----- CREATING TABLE BATSMAN
CREATE TABLE IF NOT EXISTS BATSMAN(
	BAT_1ST varchar(10	),	
	RUNS	varchar(10	),
	BF	varchar(10),
	SR	varchar(10	),
	FOURS	varchar(10	),
	SIXES	varchar(10	),
	OPPOSITION	varchar(20	),
	GROUND	varchar(30	),
	START_DATE	varchar(20	),
	MATCH_ID	varchar(20	),
	BATSMAN	varchar(30	),
	PLAYER_ID int
);

-- LOADING DATA OF TABEL BATSMAN

LOAD DATA INFILE
"D:\ODI_CRICKET\\Batsman_Data.csv"
INTO TABLE BATSMAN
FIELDS TERMINATED BY ","
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SET sql_mode = "";

-- CREATING TABLE BOWLER 
CREATE TABLE IF NOT EXISTS BOWLERS(
	S_NO DECIMAL(38, 0) NOT NULL, 
	OVERS VARCHAR(3) NOT NULL, 
	MDNS VARCHAR(1) NOT NULL, 
	RUNS VARCHAR(3) NOT NULL, 
	WKTES VARCHAR(1) NOT NULL, 
	ECON VARCHAR(5) NOT NULL, 
	AVE VARCHAR(5) NOT NULL, 
	S_RATE VARCHAR(4) NOT NULL, 
	OPPOSITION VARCHAR(14) NOT NULL, 
	GROUND VARCHAR(21) NOT NULL, 
	START_DATE VARCHAR(9) NOT NULL, 
	MATCH_ID VARCHAR(10) NOT NULL, 
	BOWLER VARCHAR(21) NOT NULL, 
	PLAYER_ID DECIMAL(38, 0) NOT NULL

);

-- LOADING DATA OF TABLE BOWLER
LOAD DATA INFILE 
"D:\ODI_CRICKET\\Bowler_Data.csv"
INTO TABLE BOWLERS
FIELDS TERMINATED BY ","
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

-- CREATING TABLE ODI_MATCH_RESULT
CREATE TABLE ODI_MATCH_RESULT(
	RESULT VARCHAR(4) NOT NULL, 
	MARGIN VARCHAR(10) NOT NULL, 
	BR DECIMAL(38, 0), 
	TOSS VARCHAR(4) NOT NULL, 
	BAT VARCHAR(3) NOT NULL, 
	OPPOSITION VARCHAR(14) NOT NULL, 
	GROUND VARCHAR(18) NOT NULL, 
	START_DATE VARCHAR(10) NOT NULL, 
	MATCH_ID VARCHAR(11) NOT NULL, 
	COUNTRY VARCHAR(11) NOT NULL, 
	COUNTRY_ID DECIMAL(38, 0) NOT NULL
);
-- LOADING DATA IN TABLE ODI_MATCH_RESULT

LOAD DATA INFILE 
"D:\ODI_CRICKET\\ODI_Match_Results.csv"
INTO TABLE ODI_MATCH_RESULT
FIELDS TERMINATED BY ","
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


