/* CREATING VIEW BATSMAN_RUNS . FIRST COLUMN CONTAIN BATSMAN NMAE AND SECOND COLUMN CONTAIN TOTAL_RUNS OF BATSMAN*/
CREATE VIEW  BATSMAN_RUNS AS
				SELECT BATSMAN, SUM(RUNS) AS TOTAL_RUNS FROM BATSMAN GROUP BY 1 ORDER BY 2 DESC;
                

/* CREATING VIEW BATSMAN_RUNS_VS_OPPOSITION. FIRST COLUMN CONTAIN BATSMAN NAME ,
SECOND COLUMN CONTAIN BATSMAN PLAYED ON OPPOSITION ,
THIRD COLUMN CONTAIN TOTAL_RUNS COUNTRY WISE ,FOURTH COLUMN CONTAIN NUMBER OF MATCH PLAYED COUNTRY WISE
AND FIFTH COLUMN CONTAIN AVERAGE OF BATSMAN COUNTRY WISE 
(IF  BATSMAN NOT_OUT IN MATCH , RUNS IS ADD BUT  MATCH IS NOT ADD  WHILE CALCULATED AVERAGE )   */
                
CREATE OR REPLACE VIEW BATSMAN_RUNS_VS_OPPOSITION AS
SELECT BATSMAN, OPPOSITION, SUM(RUNS) AS TOTAL_RUNS ,COUNT(*) AS TOTAL_MATCH_PLAYED ,
			ROUND(SUM(RUNS)/SUM(CASE 
									WHEN `OUT/NOT_OUT`='NOT OUT' THEN "0"
                                    ELSE "1" 
                                    END  ) ,2)AS AVERAGE 
									FROM BATSMAN GROUP BY 1,2 ORDER BY 1,3 DESC;
                                    
/* CREATING VIEW FOURS_SIXES FROM TABLE BATSMAN*/
CREATE OR REPLACE VIEW BATSMAN_FOUR_SIXES AS 
              SELECT BATSMAN ,SUM(FOURS) AS  TOTAL_FOURS,SUM(SIXES) AS TOTAL_SIXES FROM BATSMAN GROUP BY 1 ORDER BY 3 DESC;

/*CREATING VIEW BOWLER_WICKETS EXTRECT BOWLER NAME AND  THERE WICKET IN MATCHES */
CREATE OR REPLACE VIEW BOWLER_WICKTES AS
			 SELECT BOWLER,SUM(WKTES) AS TOTAL_WICKETS ,COUNT(*) AS TOTAL_MATCH  
			 FROM BOWLERS GROUP BY 1 ORDER BY 2 DESC;

/* CREATING VIEW BOWLER_OPPOSITION_DETAIL */
CREATE OR REPLACE VIEW BOWLER_OPPOSITION_DETAIL AS
				SELECT BOWLER ,OPPOSITION,SUM(MDNS) AS TOTAL_MDNS,SUM(OVERS) AS TOTAL_OVERS ,SUM(RUNS) AS RUN_CONSIDER,
				ROUND(SUM(RUNS)/SUM(OVERS),2) AS ECON,SUM(WKTES) AS TOTAL_WICKETS  ,ROUND(SUM(RUNS)/SUM(WKTES),2) AS AVERAGE ,
				COUNT(*) AS TOTAL_MATCH FROM BOWLERS GROUP BY 1,2 ORDER BY 1;
                
                

/* CREATING VIEW COUNTRY_TOSS_FAVOUR ,COLUMN LIKE COUNTRY ,TOSS ,BAT(1ST/2ND) ,RESULT,TOTAL_MATCH  */
CREATE OR REPLACE VIEW COUNTRY_TOSS_FAVOUR AS
							SELECT COUNTRY,TOSS, BAT ,RESULT ,COUNT(*) AS TOTAL_MATCH FROM ODI_MATCH_RESULT 
                            GROUP BY 1 ,2 ,3 ORDER BY 1;

/* CREATING VIEW COUNTRY_WIN_LOSS_MATCHES COUNTRY WIN OR LOSE FROM OPPOSITION COUNTRY IN YEAR*/
CREATE OR REPLACE VIEW COUNTRY_WIN_LOSS_MATCHES AS
			SELECT COUNTRY,OPPOSITION,RESULT, COUNT(*) AS TOTAL_MATCH ,CONCAT(MIN(YEAR(START_DATE)),'-', MAX(YEAR(START_DATE))) 
            AS BETWEEN_YEARS  FROM ODI_MATCH_RESULT GROUP BY 1,2,3 ORDER BY 1,3,4; 
            