/*SELECT  ALL INFORMATION  OF "BATSMAN" TABLE.*/
SELECT * FROM BATSMAN;

/* EXTRACT ALL RECORDS OF BATSMAN ,RUNS AND MATCH PLAYED */
SELECT BATSMAN,SUM(RUNS) AS TOTAL_RUNS ,COUNT(*) AS TOTAL_MATCH FROM BATSMAN GROUP BY 1 ORDER BY 2 DESC;


/* EXTRACT ALL RECORDS OF BATSMAN ,RUNS , MATCH PLAYED AND BATSMAN PLAYED IN YEARS*/
SELECT BATSMAN,SUM(RUNS) AS TOTAL_RUNS ,COUNT(*) AS TOTAL_MATCH,
			CONCAT(MIN(YEAR(START_DATE)) ,"-" ,MAX(YEAR(START_DATE))) AS PLAYED_YEAR FROM BATSMAN GROUP BY 1 ORDER BY 2 DESC;
            
/*DETAIL OF BATSMAN HAS  HIGHEST SCORE IN ODI   */
SELECT * FROM BATSMAN ORDER BY RUNS DESC LIMIT 1 ;


/* EXTRECT ALL NO OF MATCH  AND  RUNS IN DIFFERENT COUNTRY*/
SELECT BATSMAN ,OPPOSITION ,SUM(RUNS) AS TOTAL_RUNS,COUNT(*) AS TOTAL_MATCH  FROM BATSMAN GROUP BY 1,2;

/* WHICH BATSMAN HAS MOST NOT OUT */
SELECT BATSMAN,COUNT(*) AS TOTAL_NOT_OUT FROM BATSMAN WHERE `OUT/NOT_OUT`= 'NOT OUT' GROUP BY 1 ORDER BY 2 DESC;

/* TOP 5 BATSMAN HIT MAXIMUM SISES IN MATCHS */
SELECT BATSMAN, SUM(SIXES) AS TOTAL_SIXES, COUNT(*) AS TOTAL_MATCHES FROM BATSMAN GROUP BY 1 ORDER BY 2 DESC LIMIT 5;


/* TOP 5 BATSMAN HIT MAXIMUM FOURS IN MATCHS*/
SELECT BATSMAN, SUM(FOURS) AS TOTAL_FOURS, COUNT(*) AS TOTAL_MATCHES FROM BATSMAN GROUP BY 1 ORDER BY 2 DESC LIMIT 5;

/* EXTRACT ALL "BATSMAN NAME"  "TOTAL RUNS" MORE THEN 5000 AND "TOTAL MATCH PLAYED"   */
SELECT BATSMAN ,SUM(RUNS) AS TOTAL_RUN ,COUNT(*) AS TOTAL_MATCH FROM BATSMAN  GROUP BY 1 HAVING SUM(RUNS)>5000 ORDER BY 2 DESC LIMIT 5;







/* SELECT  ALL INFORMATION  OF "BOWLERS" TABLE.  */
SELECT * FROM BOWLERS;


/* EXTRECT  3 COLUMNS . FIRST COLUMNS CONTAINS BOWLER NAME ,SECOND COLUMNS CONTAINS  
													WICKETS AND  THIRD COLUMNS CONTAINS YEARS*/

SELECT BOWLER ,SUM(WKTES) AS TOTAL_WICKETS ,CONCAT(MIN(YEAR(START_DATE)), "-", MAX(YEAR(START_DATE))) 
										AS IN_YEARS FROM BOWLERS GROUP BY 1 ORDER BY 2 DESC;

/*TOP 5 WICKETS TAKING  BOWLER  */
SELECT BOWLER ,SUM(WKTES) AS TOAL_WICKETS FROM BOWLERS GROUP BY 1 ORDER BY 2 DESC LIMIT 5;

/*EXTRECT BOWLER NAME ,  ECONOMIC  AND AVERAGE OF  BOWLERS  */
SELECT BOWLER, ROUND(SUM(RUNS)/SUM(OVERS),2) AS ECON , 
			   ROUND(SUM(RUNS)/SUM(WKTES),2) AS AVE FROM BOWLERS GROUP BY 1 ORDER BY 2;

/* BOWLER TAKE MAXIMUM WICKETS IN A INNING*/
SELECT BOWLER,MAX(WKTES) AS WKTES_IN_INNING FROM BOWLERS GROUP BY BOWLER  ORDER BY 2 DESC;

/*HOW MANY TIMES BOWLER TAKE FIVE WKCKETS OR MORE*/

SELECT BOWLER,COUNT(*) AS TIMES_5WKTES FROM BOWLERS WHERE WKTES >=5 GROUP BY 1 ORDER BY 2 DESC;

/* NUMBERS OF MDNS OVER BOWL BY THE BOWLERS*/
SELECT BOWLER,SUM(MDNS) AS TOTAL_MDNS_OVERS FROM BOWLERS GROUP BY 1 ORDER BY 2 DESC;



/* SELECT  ALL INFORMATION  OF "ODI_MATCH_RESULT" TABLE.  */
SELECT * FROM ODI_MATCH_RESULT;

----- TOTAL COUNTRY WHO PLAY ODI CRICKET
SELECT DISTINCT COUNTRY FROM ODI_MATCH_RESULT;

/*COUNTRY WIN OR LOSE NUMBER OF MATCHES  */
SELECT COUNTRY,RESULT,COUNT(*) AS TOTAL_MATCHES FROM ODI_MATCH_RESULT GROUP BY 1,2 ORDER BY 1;

/* TOSS IN FAVOR OF COUNTRY*/
SELECT COUNTRY, TOSS, RESULT ,COUNT(*) AS TOTAL_MATCH FROM ODI_MATCH_RESULT GROUP BY 1,2,3 ORDER BY 1;

/* COUNTRY ,TOSS ,BAT(1ST/2ND) ,RESULT,TOTAL_MATCH  */
SELECT COUNTRY,TOSS, BAT ,RESULT ,COUNT(*) AS TOTAL_MATCH FROM ODI_MATCH_RESULT GROUP BY 1 ,2 ,3 ORDER BY 1;

/* COUNTRY WIN OR LOSE FROM OPPOSITION COUNTRY IN YEAR*/
SELECT COUNTRY,OPPOSITION,RESULT, COUNT(*) AS TOTAL_MATCH ,CONCAT(MIN(YEAR(START_DATE)),'-', MAX(YEAR(START_DATE))) 
            AS BETWEEN_YEARS  FROM ODI_MATCH_RESULT GROUP BY 1,2,3 ORDER BY 1,3,4; 


